version: "3.8"
services:
  nodeserver:
    build:
      context: .
      dockerfile: .docker/services/nodejs/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/app
      - /var/www/app/src/node_modules
      - ./storage:/var/www/storage
    env_file:
      - .env
  nginx:
    restart: always
    build:
      context: ./.docker/services/nginx
    ports:
      - "9900:80"
    depends_on:
      - nodeserver